repos:
  - repo: local
    hooks:
      - id: update-last-updated
        name: Update Last Updated field
        entry: python3 .github/hooks/update_last_updated.py
        language: python
        files: \.(md|mdx)$  # This matches both .md and .mdx files
        types: [file]  # Make sure it only runs on changed files
